#define WIFI_SSID "MyNetwork"
#define WIFI_PASSWORD "MyPassword"
#define CAR_ACCELERATELEFT 18
#define CAR_REVERSELEFT 19
#define CAR_ACCELERATERIGHT 22
#define CAR_REVERSERIGHT 23
#define PS4_MAC "03:03:03:03:03:03"